version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout

      # Restaurar caché si existe
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      # Instalar dependencias
      - python/install-packages:
          pkg-manager: pip

      # Guardar caché de dependencias para acelerar futuros builds
      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # Ejecutar pruebas
      - run:
          name: Run tests
          command: pytest

workflows:
  sample:
    jobs:
      - build-and-test
